-- ============================================================================
-- PRISM - Database Initialization Script
-- ============================================================================
--
-- WHAT THIS FILE DOES:
-- This SQL script runs automatically when the PostgreSQL container starts
-- for the first time. It sets up:
--   1. Required PostgreSQL extensions
--   2. Initial database configuration
--
-- HOW IT WORKS:
-- Docker mounts this file into /docker-entrypoint-initdb.d/
-- PostgreSQL runs all .sql files in that directory on first startup.
--
-- FILE NAMING:
-- Files are executed in alphabetical order, so we prefix with numbers:
--   01-init.sql    (this file - extensions and config)
--   02-schema.sql  (table definitions - generated by Drizzle)
--   03-seed.sql    (initial data - optional)
--
-- IMPORTANT:
-- This file ONLY runs on first container creation.
-- To re-run it, you need to delete the Docker volume:
--   docker-compose down -v
--   docker-compose up -d
--
-- ============================================================================


-- ============================================================================
-- ENABLE UUID EXTENSION
-- ============================================================================
-- UUIDs (Universally Unique Identifiers) are used for primary keys.
-- They're better than auto-increment IDs for distributed systems and security.
--
-- Example UUID: 550e8400-e29b-41d4-a716-446655440000
--
-- Benefits of UUIDs:
-- - Globally unique (no collisions across systems)
-- - Can be generated client-side (no round-trip to database)
-- - Harder to guess/enumerate than sequential IDs
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Also enable gen_random_uuid() which is faster
-- Available in PostgreSQL 13+ (we use 15)
-- This is what Drizzle's defaultRandom() uses


-- ============================================================================
-- ENABLE FULL TEXT SEARCH (for future use)
-- ============================================================================
-- Full text search enables powerful search capabilities.
-- We might use this for searching events, tasks, notes, etc.
--
-- Example usage:
--   SELECT * FROM events WHERE to_tsvector(title || ' ' || description) @@ to_tsquery('meeting');
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS "pg_trgm";


-- ============================================================================
-- CONFIGURE DATABASE SETTINGS
-- ============================================================================
-- These settings optimize PostgreSQL for our use case.
-- They're applied to this database only, not the entire server.
-- ============================================================================

-- Set the timezone to UTC for consistency
-- All dates are stored in UTC, converted to local time in the app
SET timezone = 'UTC';


-- ============================================================================
-- CREATE HELPER FUNCTIONS
-- ============================================================================
-- Reusable SQL functions used throughout the schema.
-- ============================================================================

-- Function to update 'updated_at' timestamp automatically
-- This is used by triggers on tables with updated_at columns
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- ============================================================================
-- INFORMATIONAL OUTPUT
-- ============================================================================
-- Print a message so we can see this script ran in the logs.
-- ============================================================================

DO $$
BEGIN
    RAISE NOTICE '
================================================================================
PRISM Database Initialization Complete
================================================================================
Extensions enabled:
  - uuid-ossp (UUID generation)
  - pg_trgm (fuzzy text search)

Functions created:
  - update_updated_at_column() (auto-update timestamps)

Next steps:
  - Run migrations with: npm run db:migrate
  - Or push schema with: npm run db:push

================================================================================
';
END $$;
