#!/bin/bash
# ============================================================================
# Prism - One-Command Installer
# ============================================================================
# Usage: curl -fsSL https://raw.githubusercontent.com/sandydargoport/prism/master/scripts/install.sh | bash
# Or locally: ./scripts/install.sh
# ============================================================================

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log() { echo -e "${BLUE}[Prism]${NC} $1"; }
success() { echo -e "${GREEN}[Prism]${NC} $1"; }
warn() { echo -e "${YELLOW}[Prism]${NC} $1"; }
error() { echo -e "${RED}[Prism]${NC} $1"; exit 1; }

# Banner
echo ""
echo -e "${BLUE}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║                                                            ║${NC}"
echo -e "${BLUE}║${NC}     ${GREEN}PRISM${NC} - Your Family's Digital Home                    ${BLUE}║${NC}"
echo -e "${BLUE}║                                                            ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""

# Check prerequisites
log "Checking prerequisites..."

if ! command -v docker &> /dev/null; then
    error "Docker is not installed. Please install Docker first: https://docs.docker.com/get-docker/"
fi

if ! docker compose version &> /dev/null && ! docker-compose version &> /dev/null; then
    error "Docker Compose is not installed. Please install Docker Compose: https://docs.docker.com/compose/install/"
fi

# Detect docker compose command
if docker compose version &> /dev/null; then
    COMPOSE="docker compose"
else
    COMPOSE="docker-compose"
fi

success "Docker and Docker Compose are installed"

# Clone if not in prism directory
if [ ! -f "docker-compose.yml" ]; then
    log "Cloning Prism repository..."
    if [ -d "prism" ]; then
        warn "Directory 'prism' already exists. Using existing directory."
        cd prism
    else
        git clone https://github.com/sandydargoport/prism.git
        cd prism
    fi
fi

# Generate secure random strings
generate_secret() {
    # Try different methods in order of preference
    if command -v openssl &> /dev/null; then
        openssl rand -hex 32
    elif command -v python3 &> /dev/null; then
        python3 -c "import secrets; print(secrets.token_hex(32))"
    elif command -v node &> /dev/null; then
        node -e "console.log(require('crypto').randomBytes(32).toString('hex'))"
    else
        # Fallback: use /dev/urandom
        head -c 32 /dev/urandom | xxd -p | tr -d '\n'
    fi
}

# Create .env file if it doesn't exist
if [ ! -f ".env" ]; then
    log "Creating .env file with secure defaults..."

    DB_PASSWORD=$(generate_secret)
    SESSION_SECRET=$(generate_secret)
    PIN_ENCRYPTION_KEY=$(generate_secret)

    cat > .env << EOF
# Generated by Prism installer on $(date)
# Edit this file to add your API keys for integrations

# Database (auto-generated - don't change unless you know what you're doing)
DATABASE_URL=postgresql://prism:${DB_PASSWORD}@db:5432/prism
DB_PASSWORD=${DB_PASSWORD}

# Redis
REDIS_URL=redis://redis:6379

# Application
NODE_ENV=production
PORT=3000
APP_URL=http://localhost:3000

# Security secrets (auto-generated)
SESSION_SECRET=${SESSION_SECRET}
PIN_ENCRYPTION_KEY=${PIN_ENCRYPTION_KEY}

# ============================================================================
# OPTIONAL INTEGRATIONS
# Uncomment and fill in to enable these features
# See .env.example for detailed instructions
# ============================================================================

# Google Calendar
# GOOGLE_CLIENT_ID=
# GOOGLE_CLIENT_SECRET=
# GOOGLE_REDIRECT_URI=http://localhost:3000/api/auth/google/callback

# Microsoft To Do / OneDrive
# MICROSOFT_CLIENT_ID=
# MICROSOFT_CLIENT_SECRET=
# MICROSOFT_REDIRECT_URI=http://localhost:3000/api/auth/microsoft/callback

# Weather (OpenWeatherMap - free tier)
# OPENWEATHER_API_KEY=
# WEATHER_LOCATION=Springfield,IL,US
EOF

    success "Created .env with auto-generated secrets"
else
    warn ".env file already exists, skipping generation"
fi

# Create necessary directories
mkdir -p uploads backups data/photos config

# Build and start containers
log "Building and starting containers (this may take a few minutes)..."
$COMPOSE up -d --build

# Wait for health check
log "Waiting for Prism to start..."
MAX_ATTEMPTS=60
ATTEMPT=0

while [ $ATTEMPT -lt $MAX_ATTEMPTS ]; do
    if curl -sf http://localhost:3000/api/health > /dev/null 2>&1; then
        break
    fi
    ATTEMPT=$((ATTEMPT + 1))
    echo -n "."
    sleep 2
done
echo ""

if [ $ATTEMPT -eq $MAX_ATTEMPTS ]; then
    error "Prism failed to start. Check logs with: docker logs prism-app"
fi

success "Prism is running!"

# Verify database was seeded (init scripts handle this automatically)
log "Verifying database setup..."
FAMILY_COUNT=$(docker exec prism-db psql -U prism -d prism -t -c "SELECT COUNT(*) FROM users;" 2>/dev/null | tr -d ' ' || echo "error")

if [ "$FAMILY_COUNT" = "error" ]; then
    warn "Could not verify database. Check logs with: docker logs prism-app"
elif [ "$FAMILY_COUNT" = "0" ]; then
    warn "Database tables exist but no seed data found. You can seed manually via Settings > Admin."
else
    success "Database ready with $FAMILY_COUNT family members"
fi

# Final message
echo ""
echo -e "${GREEN}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║                                                            ║${NC}"
echo -e "${GREEN}║${NC}     Prism is ready!                                        ${GREEN}║${NC}"
echo -e "${GREEN}║                                                            ║${NC}"
echo -e "${GREEN}║${NC}     Open ${BLUE}http://localhost:3000${NC} in your browser           ${GREEN}║${NC}"
echo -e "${GREEN}║                                                            ║${NC}"
echo -e "${GREEN}║${NC}     Default PIN: ${YELLOW}1234${NC} (parent) or ${YELLOW}0000${NC} (child)            ${GREEN}║${NC}"
echo -e "${GREEN}║                                                            ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "Next steps:"
echo -e "  1. Open Prism and log in with PIN ${YELLOW}1234${NC}"
echo -e "  2. Go to Settings to add your family members"
echo -e "  3. Edit ${BLUE}.env${NC} to add calendar/task integrations"
echo -e ""
echo -e "Useful commands:"
echo -e "  ${BLUE}$COMPOSE logs -f app${NC}     # View logs"
echo -e "  ${BLUE}$COMPOSE restart app${NC}     # Restart app"
echo -e "  ${BLUE}$COMPOSE down${NC}            # Stop all containers"
echo -e ""

# Try to open browser (optional, won't fail if unavailable)
if command -v xdg-open &> /dev/null; then
    xdg-open http://localhost:3000 2>/dev/null &
elif command -v open &> /dev/null; then
    open http://localhost:3000 2>/dev/null &
fi
